blank_issues_enabled: false
contact_links:
  - name: 📚 Гайды по подготовке диплома
    url: https://github.com/VikZarip/mirea-iptip-diploma-topics/blob/main/diploma-info/guides/README.md
    about: Методология, проектирование, оформление, защита
  - name: 📖 Каталог доступных тем
    url: https://github.com/VikZarip/mirea-iptip-diploma-topics/blob/main/diploma-info/topics/README.md
    about: Просмотрите темы со статусом "Свободно"
  - name: 💬 Обсуждения и вопросы
    url: https://github.com/VikZarip/mirea-iptip-diploma-topics/discussions
    about: Задайте вопрос куратору или обсудите с другими студентами
