name: Предложение новой темы
description: Студент предлагает свою тему дипломного проекта на рассмотрение
labels: [topic-proposal]
title: "[Предложение] <краткое название темы>"
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Предложение новой темы дипломного проекта
        
        Заполните форму для предложения своей темы. После рассмотрения куратором тема будет добавлена в каталог или отправлена на доработку.

  - type: input
    id: fio
    attributes:
      label: ФИО студента
      placeholder: Иванов Иван Иванович
    validations:
      required: true

  - type: input
    id: group
    attributes:
      label: Группа
      placeholder: ИКБО-01-21
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Название темы
      description: Полное название дипломной работы
      placeholder: Система прогнозирования нагрузки на серверы с использованием машинного обучения
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: Предлагаемый slug
      description: Короткое имя для файла темы (латиница, через дефис)
      placeholder: server-load-forecasting
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Краткое описание
      description: Опишите суть темы и ключевую проблему (2-4 предложения)
      placeholder: |
        Создание системы для прогнозирования нагрузки на серверы компании...
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: Ожидаемый результат
      description: Что именно будет на выходе? Какие отчётные материалы?
      placeholder: |
        - Модель прогнозирования нагрузки
        - Веб-панель мониторинга
        - Научная статья
    validations:
      required: true

  - type: textarea
    id: functions
    attributes:
      label: Возможные функции/компоненты
      description: Перечислите основные функции и компоненты системы
      placeholder: |
        - Сбор метрик с серверов
        - ETL-пайплайн
        - ML-модели для прогнозирования
    validations:
      required: true

  - type: textarea
    id: tech_stack
    attributes:
      label: Технологический стек
      description: Предполагаемые технологии, библиотеки, платформы
      placeholder: |
        - Python (Pandas, scikit-learn, XGBoost)
        - PostgreSQL
        - Docker
    validations:
      required: false

  - type: textarea
    id: use_cases
    attributes:
      label: Основные сценарии использования
      description: Опишите ключевые use cases (роли, шаги, результаты)
      placeholder: |
        - Администратор просматривает прогноз нагрузки на 24 часа
        - Система автоматически масштабирует ресурсы при превышении порога
    validations:
      required: true

  - type: textarea
    id: novelty
    attributes:
      label: Научная новизна и актуальность
      description: Обоснуйте новизну и актуальность темы
      placeholder: |
        Существующие решения не учитывают специфику...
    validations:
      required: true

  - type: textarea
    id: methods
    attributes:
      label: Методы, модели и данные
      description: Какие методы/модели планируете использовать? Откуда данные?
      placeholder: |
        - Методы: LSTM, Prophet, XGBoost
        - Данные: метрики Prometheus, логи nginx
    validations:
      required: false

  - type: textarea
    id: practical_value
    attributes:
      label: Практическая польза
      description: Какой эффект и для кого? Метрики успеха?
      placeholder: |
        - Снижение затрат на инфраструктуру на 20%
        - Предотвращение простоев сервисов
    validations:
      required: true

  - type: textarea
    id: data_sources
    attributes:
      label: Источники данных
      description: Укажите открытые или внутренние источники данных (если применимо)
      placeholder: |
        - Kaggle Dataset: Server Metrics
        - Внутренние метрики компании
    validations:
      required: false

  - type: input
    id: supervisor
    attributes:
      label: Научный руководитель (если согласован)
      value: Зарипова В.М.
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Дополнительная информация
      description: Любая другая важная информация о теме
    validations:
      required: false
