name: Резервация темы
description: Заявка студента на резервацию темы
labels: [reservation]
title: "[Заявка] ФИО — <slug>"
body:
  - type: markdown
    attributes:
      value: |
        Заполните форму. После создания заявки тема будет автоматически переведена в статус «Зарезервирована», если свободна.
  - type: input
    id: fio
    attributes:
      label: ФИО студента
      placeholder: Иванов Иван Иванович
    validations:
      required: true
  - type: input
    id: group
    attributes:
      label: Группа
      placeholder: ИКБО-01-21
    validations:
      required: true
  - type: dropdown
    id: slug
    attributes:
      label: Выберите тему
      description: Список автоматически обновляется и содержит только свободные темы. Проверьте актуальность в каталоге topics/
      options:
        - air-pollution-forecast | Прогноз уровня загрязнения воздуха
        - api-designer-event-model | API-дизайнер на основе событийной модели
        - chronic-disease-classification | Классификация хронических заболеваний
        - client-complaints-routing | Маршрутизация жалоб клиентов
        - conflict-of-interest-detection | Детекция конфликтов интересов
        - environmental-disaster-warning | Система раннего предупреждения о ЧС
        - event-storming-interactive | Интерактивный Event Storming
        - medical-staff-allocation | Распределение медперсонала
        - multi-apartment-energy-management | Управление энергопотреблением в МКД
        - pandemic-early-warning | Раннее предупреждение о пандемиях
        - platform-family-support | Платформа поддержки семей
        - requirements-deduplication | Дедупликация требований
        - social-benefits-fraud-detection | Детекция мошенничества с соцвыплатами
        - social-workers-routing | Маршрутизация социальных работников
        - urban-air-quality-monitoring | Мониторинг качества воздуха в городе
        - utility-consumption-forecast | Прогноз потребления коммунальных услуг
    validations:
      required: true
  - type: input
    id: supervisor
    attributes:
      label: Научный руководитель
      value: Зарипова В.М.
    validations:
      required: true
  - type: input
    id: access_code
    attributes:
      label: Код доступа
      description: Получите код у куратора. Заявки без корректного кода автоматически отклоняются.
      placeholder: XXXXX
    validations:
      required: true
