name: Topic Proposal Handler

on:
  issues:
    types: [opened]

jobs:
  handle-proposal:
    if: contains(github.event.issue.labels.*.name, 'topic-proposal') || startsWith(github.event.issue.title, '[Предложение]')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add acknowledgment comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `👋 Спасибо за предложение новой темы!

**Студент:** ${{ github.event.issue.user.login }}

---

### Что дальше?

1. **Куратор рассмотрит** ваше предложение в ближайшее время
2. Возможно, потребуются **уточнения или доработка** — следите за комментариями
3. После одобрения тема будет **добавлена в каталог** и вы сможете её зарезервировать

### Критерии оценки:

✅ **Актуальность** — решает ли тема реальную проблему?  
✅ **Реализуемость** — можно ли выполнить за отведённое время?  
✅ **Научная ценность** — есть ли элементы исследования?  
✅ **Практическая польза** — кому и как это поможет?

**Ожидайте ответа куратора в этом Issue.** 📧`
            });
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['pending-review']
            });
